"""phase3 sheet cache_path

Revision ID: eceb2358f070
Revises: f1129373cd6a
Create Date: 2026-07-03 16:35:04.535494

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eceb2358f070'
down_revision: Union[str, None] = 'f1129373cd6a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('dataset_sheets', sa.Column('cache_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('dataset_sheets', 'cache_path')
    # ### end Alembic commands ###
